In [1]:
def altitude (T):
    """determine the altitude in km of a satellite based on period of orbit in minutes"""
    G = 6.67*10**(-11)
    M = 5.97*10**24
    R = 6371
    pi = 3.14159265358979
    constant = ((G*M*(60**2)/(4*(pi**2))))      #value 60^2 from converting units of time from minutes to seconds
    altitude = (constant*(T**2))**(1/3) - R
    return altitude

c=altitude(10)  
print(c)

1530654.1590033714


In [14]:
import numpy as np

#Simple e**-x

list_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numbers = np.array(list_1)
print(numbers)

for x in numbers:
    expx=0.0
    #print(numbers[x])
    for n in range(0, 1001):
        expx += (((-1)**n)*(((numbers[x]*10)**n)/(np.math.factorial(n))))
    print(x*10,expx,np.exp(-x*10))

[ 0  1  2  3  4  5  6  7  8  9 10]
0 1.0 1.0
10 -1056.7510164765213 4.5399929762484854e-05
20 -192667.14269339206 2.061153622438558e-09
30 738219.3571055843 9.357622968840175e-14
40 -1172614.9729100529 4.248354255291589e-18
50 -4447163.6323095 1.9287498479639178e-22
60 -6649010.296760228 8.75651076269652e-27
70 -11090626.416535772 3.975449735908647e-31
80 10478680.009523809 1.8048513878454153e-35
90 -12605034.41855839 8.194012623990515e-40
100 -8759659.53363931 3.720075976020836e-44


In [1]:
import numpy as np

#Inverse e**-x

list_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]                     #defined the array to work with
numbers = np.array(list_1)
print(numbers)                                                  #checked my array

for x in numbers:
    expi=0.0
    #print(numbers[x])
    for n in range(0,1001):
        expi += ((-numbers[x]*10)**n/(np.math.factorial(n)))    #after setting x and n, define funcion
    print(x*10,1/expi, np.exp(-x*10))                           #print 3 columns, x value, inverse of s_n, and actual
    
    
    #obviously much closer than simple, though for some strange reason everything is negative

[ 0  1  2  3  4  5  6  7  8  9 10]
0 1.0 1.0
10 -0.0009462967003658594 4.5399929762484854e-05
20 -5.190298594874512e-06 2.061153622438558e-09
30 1.3546109166262004e-06 9.357622968840175e-14
40 -8.527948415312504e-07 4.248354255291589e-18
50 -2.248624252849181e-07 1.9287498479639178e-22
60 -1.5039832326432947e-07 8.75651076269652e-27
70 -9.016623249603211e-08 3.975449735908647e-31
80 9.543186728587237e-08 1.8048513878454153e-35
90 -7.933338115504866e-08 8.194012623990515e-40
100 -1.141596880746046e-07 3.720075976020836e-44


In [2]:
import numpy as np

#Recursive e**-x

def s_n(y,z):                                     #set to define the recursive formula
    """to define a recursive s_n according to the summation of e**-x"""
    if y==0:                                      #needed a starting point so it wouldn't recurse negatively
        return 1
    else:
        return (-s_n(y-1,z)*(z/y))                #actual desired function

list_1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]       #defined the array to work with
numbers = np.array(list_1)
print(numbers)                                    #array check

for x in numbers:
    expr=0.0
    for n in range(0,1001):
        expr += s_n(n,numbers[x]*10)              #summation for various values of x for previously defined function
    print(x*10, expr, np.exp(-x*10))              #print 3 columns, x value, simple version, and actual
    
    
    #knowing that this is supposed to be the second most accurate method there is something strange going on here

[ 0  1  2  3  4  5  6  7  8  9 10]
0 1.0 1.0
10 4.539992967040021e-05 4.5399929762484854e-05
20 6.147561828914626e-09 2.061153622438558e-09
30 6.1030424788918156e-06 9.357622968840175e-14
40 0.3116951588217358 4.248354255291589e-18
50 2041.8329628976246 1.9287498479639178e-22
60 722745700.9303185 8.75651076269652e-27
70 4594081207253.4 3.975449735908647e-31
80 2.4508201170456323e+17 1.8048513878454153e-35
90 -5.865799310261735e+21 8.194012623990515e-40
100 8.144652745098073e+25 3.720075976020836e-44
